# submitted Section 1 Exercises in TopHat

In [273]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "David"],
"Age": [25, 30, 35, 40],
"City": ["NYC", "LA", "Chicago", "Miami"],
"Email": ["a@example.com", "b@example.com", "c@example.com", "d@example.com"],
}

df = pd.DataFrame(data)

In [274]:
df = pd.DataFrame(data)
no_email = df.drop(columns= ['Email'])
print(no_email)

      Name  Age     City
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago
3    David   40    Miami

In [275]:
df.drop(df.index[2], inplace=True)
print(df)

    Name  Age   City          Email
0  Alice   25    NYC  a@example.com
1    Bob   30     LA  b@example.com
3  David   40  Miami  d@example.com

In [276]:
data = {
"Name": ["Alice", "Bob", "Charlie", "David"],
"Age": [25, 30, 35, 40],
"City": ["NYC", "LA", "Chicago", "Miami"],
"Email": ["a@example.com", "b@example.com", "c@example.com", "d@example.com"],
}

df = pd.DataFrame(data)

df = df.drop(columns=['City', 'Email'])
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [277]:
data = {
"Name": ["Alice", "Bob", "Charlie", "David"],
"Age": [25, 30, 35, 40],
"City": ["NYC", "LA", "Chicago", "Miami"],
"Email": ["a@example.com", "b@example.com", "c@example.com", "d@example.com"],
}

df = pd.DataFrame(data)

df_trimmed = df.drop([df.index[0], df.index[-1]])
print(df_trimmed)

      Name  Age     City          Email
1      Bob   30       LA  b@example.com
2  Charlie   35  Chicago  c@example.com

In [278]:
import pandas as pd
import numpy as np

data = {
"Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
"Age": [25, np.nan, 35, 40, None],
"City": ["NYC", "LA", None, "Miami", "Boston"],
}

df = pd.DataFrame(data)

In [279]:
df.head()

      Name   Age    City
0    Alice  25.0     NYC
1      Bob   NaN      LA
2  Charlie  35.0     NaN
3    David  40.0   Miami
4      Eva   NaN  Boston

In [280]:
df.isna()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [281]:
df.isna().sum()

Name    0
Age     2
City    1
dtype: int64

In [282]:
df.dropna()

    Name   Age   City
0  Alice  25.0    NYC
3  David  40.0  Miami

In [283]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
print(df)

      Name        Age    City
0    Alice  25.000000     NYC
1      Bob  33.333333      LA
2  Charlie  35.000000     NaN
3    David  40.000000   Miami
4      Eva  33.333333  Boston

In [284]:
df['City'] = df['City'].fillna("Unknown")
print(df)

      Name        Age     City
0    Alice  25.000000      NYC
1      Bob  33.333333       LA
2  Charlie  35.000000  Unknown
3    David  40.000000    Miami
4      Eva  33.333333   Boston

In [285]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Diana"],
"Age": [25, 30, 35, 25, 30, 40],
"City": ["NYC", "LA", "SF", "NYC", "LA", "NYC"],
}

df = pd.DataFrame(data)

In [286]:
df.duplicated()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [287]:
df.drop_duplicates(keep='first')

      Name  Age City
0    Alice   25  NYC
1      Bob   30   LA
2  Charlie   35   SF
5    Diana   40  NYC

In [288]:
df.drop_duplicates(keep='last')

      Name  Age City
2  Charlie   35   SF
3    Alice   25  NYC
4      Bob   30   LA
5    Diana   40  NYC

In [289]:
df.drop_duplicates(keep=False)

      Name  Age City
2  Charlie   35   SF
5    Diana   40  NYC

In [290]:
import pandas as pd

data = {
"fname": ["Alice", "Bob", "Charlie"],
"lname": ["Smith", "Jones", "Brown"],
"ctry": ["USA", "Canada", "UK"],
}

df = pd.DataFrame(data)

In [294]:
df  = df.rename(columns = {
    'fname' : 'FirstName',
    'lname' : 'LastName'
})

print(df)

  First Name Last Name    ctry
0      Alice     Smith     USA
1        Bob     Jones  Canada
2    Charlie     Brown      UK

In [296]:
df.columns = ['FirstName', 'LastName', 'Country']
print(df)

  FirstName LastName Country
0     Alice    Smith     USA
1       Bob    Jones  Canada
2   Charlie    Brown      UK

In [300]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie"],
"Dept": ["HR", "Finance", "IT"],
"Sal": [60000, 70000, 80000],
}

df = pd.DataFrame(data)

In [301]:
df = df.rename(columns = {
    'Dept' : 'Department', 
    'Sal' : 'Salary'
})

print(df)

      Name Department  Salary
0    Alice         HR   60000
1      Bob    Finance   70000
2  Charlie         IT   80000

In [306]:
df.insert(0, 'Salary', df.pop('Salary'))
print(df)

   Salary     Name Department
0   60000    Alice         HR
1   70000      Bob    Finance
2   80000  Charlie         IT

In [307]:
print(df)

   Salary     Name Department
0   60000    Alice         HR
1   70000      Bob    Finance
2   80000  Charlie         IT

In [308]:
import pandas as pd

data = {
"Store": ["A", "A", "A", "B", "B", "C", "C", "C", "C"],
"Product": ["Apples", "Oranges", "Bananas", "Apples", "Bananas", "Oranges", "Apples", "Bananas", "Bananas"],
"Sales": [100, 80, 90, 120, 110, 60, 95, 85, 75],
"Profit": [30, 25, 20, 40, 35, 15, 32, 22, 18],
}

df = pd.DataFrame(data)
print(df.head())

  Store  Product  Sales  Profit
0     A   Apples    100      30
1     A  Oranges     80      25
2     A  Bananas     90      20
3     B   Apples    120      40
4     B  Bananas    110      35

In [312]:
df.groupby('Store').agg({
    'Sales': 'mean',
    'Profit': 'mean'
})

        Sales  Profit
Store
A       90.00   25.00
B      115.00   37.50
C       78.75   21.75

In [311]:
df.groupby('Product').agg({
    'Sales': 'max',
    'Profit': 'min'
})

         Sales  Profit
Product
Apples     120      30
Bananas    110      18
Oranges     80      15

In [316]:
df.groupby('Store').agg(
    Avg_Sales=('Sales', 'mean'),
    Max_Profit=('Profit', 'max')
)

       Avg_Sales  Max_Profit
Store
A          90.00          30
B         115.00          40
C          78.75          32

In [323]:
df.groupby(['Store', 'Product']).agg({
    'Sales': 'sum'
})

               Sales
Store Product
A     Apples     100
      Bananas     90
      Oranges     80
B     Apples     120
      Bananas    110
C     Apples      95
      Bananas    160
      Oranges     60

In [347]:
import pandas as pd

df_customers = pd.DataFrame({
"CustomerName": ["Alice", "Bob", "Charlie"]
}, index=[101, 102, 103])

df_orders = pd.DataFrame({
"OrderTotal": [250, 300, 400]
}, index=[101, 102, 103])

df_cities = pd.DataFrame({
    'City': ['NYC', 'LA', 'Chicago']
}, index=[101, 102, 103])

In [330]:
result = df_customers.join(df_orders)
print(result)

    CustomerName  OrderTotal
101        Alice         250
102          Bob         300
103      Charlie         400

In [348]:
df_customers = df_customers.join(df_cities)
print(df_customers)

    CustomerName     City
101        Alice      NYC
102          Bob       LA
103      Charlie  Chicago