In [146]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "David"],
"Age": [25, 30, 35, 40],
"City": ["NYC", "LA", "Chicago", "Miami"],
"Email": ["a@example.com", "b@example.com", "c@example.com", "d@example.com"],
}

df = pd.DataFrame(data)

In [147]:
df = pd.DataFrame(data)
no_email = df.drop(columns= ['Email'])
print(no_email)

      Name  Age     City
0    Alice   25      NYC
1      Bob   30       LA
2  Charlie   35  Chicago
3    David   40    Miami

In [148]:
df.drop(df.index[2], inplace=True)
print(df)

    Name  Age   City          Email
0  Alice   25    NYC  a@example.com
1    Bob   30     LA  b@example.com
3  David   40  Miami  d@example.com

In [149]:
data = {
"Name": ["Alice", "Bob", "Charlie", "David"],
"Age": [25, 30, 35, 40],
"City": ["NYC", "LA", "Chicago", "Miami"],
"Email": ["a@example.com", "b@example.com", "c@example.com", "d@example.com"],
}

df = pd.DataFrame(data)

df = df.drop(columns=['City', 'Email'])
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40

In [150]:
data = {
"Name": ["Alice", "Bob", "Charlie", "David"],
"Age": [25, 30, 35, 40],
"City": ["NYC", "LA", "Chicago", "Miami"],
"Email": ["a@example.com", "b@example.com", "c@example.com", "d@example.com"],
}

df = pd.DataFrame(data)

df_trimmed = df.drop([df.index[0], df.index[-1]])
print(df_trimmed)

      Name  Age     City          Email
1      Bob   30       LA  b@example.com
2  Charlie   35  Chicago  c@example.com

In [151]:
import pandas as pd
import numpy as np

data = {
"Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
"Age": [25, np.nan, 35, 40, None],
"City": ["NYC", "LA", None, "Miami", "Boston"],
}

df = pd.DataFrame(data)

In [152]:
df.head()

      Name   Age    City
0    Alice  25.0     NYC
1      Bob   NaN      LA
2  Charlie  35.0     NaN
3    David  40.0   Miami
4      Eva   NaN  Boston

In [153]:
df.isna()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [154]:
df.isna().sum()

Name    0
Age     2
City    1
dtype: int64

In [155]:
df.dropna()

    Name   Age   City
0  Alice  25.0    NYC
3  David  40.0  Miami

In [156]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
print(df)

      Name        Age    City
0    Alice  25.000000     NYC
1      Bob  33.333333      LA
2  Charlie  35.000000     NaN
3    David  40.000000   Miami
4      Eva  33.333333  Boston

In [157]:
df['City'] = df['City'].fillna("Unknown")
print(df)

      Name        Age     City
0    Alice  25.000000      NYC
1      Bob  33.333333       LA
2  Charlie  35.000000  Unknown
3    David  40.000000    Miami
4      Eva  33.333333   Boston

In [ ]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Diana"],
"Age": [25, 30, 35, 25, 30, 40],
"City": ["NYC", "LA", "SF", "NYC", "LA", "NYC"],
}

df = pd.DataFrame(data)